---
title: "Week 02: Data analysis of ICP-MS data"
author: "Gillian McGinnis"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

```{r, warning=FALSE, message=FALSE}
## Data import chunk
# Importing necessary data
ICPMS_imported <- read.csv("data/ICPMS_Data.csv", skip = 1, na = "N/A")
sample_key <- read.csv("data/Sample_Key.csv", skip = 0)
```

```{r}
## Tidying chunk

RSD_data <- ICPMS_imported %>%
  # picking relevant columns + renaming them to appropraite isotopes
  select(Cr52 = CPS.RSD,
         Cr53 = CPS.RSD.1,
         As75 = CPS.RSD.2,
         Cd111 = CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key) %>%
  # making data longer
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "RSD")

view(RSD_data)


ICPMS_tidy <- ICPMS_imported %>%
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key) %>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "CPS") %>%
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS = CPS/Ge72) %>%
  select(-Ge72)
view(ICPMS_tidy)

# Confirming the RSD data matches
all(RSD_data$Sample.Key == ICPMS_tidy$Sample.Key,
    RSD_data$metal == ICPMS_tidy$metal)

ICPMS_merged <- merge(ICPMS_tidy, sample_key)
view(ICPMS_merged)
```

```{r, warning=FALSE}
##Decluttering environment
rm(list = setdiff(ls(), "ICPMS_merged"))
```

```{r}
## Deliverable
saveRDS(ICPMS_merged, file = "data/ICPMS_merged.rds")
write.csv(ICPMS_merged, file = "data/ICPMS_merged.csv")
```

